name: run-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: for s in $(find . -name *.sln); do dotnet restore $s; done
    - name: Build
      run: for s in $(find . -name *.sln); do dotnet build $s --no-restore; done
    - name: Test
      run: for s in $(find . -name *.sln); do dotnet test $s --no-build --verbosity normal; done
